<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
<head>
  <title>GRASS/PHP Server Sample page: Current Earthquakes</title>
  <meta name="Author" content="Markus Neteler, 2006">
  <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
</head>
<body bgcolor="#FFFFFF">

<h2>Recent Earthquakes: map generated by GRASS on the fly with PHP</h2>
<P>
Software: Apache, PHP5, GRASS 6 (see <a href="php_grass_earthquakes_PHP4.txt">here</a> for PHP4 example; 
 <a href="http://mpa.itc.it/markus/grass63/earthquakes/">here</a> for GRASS location with world map)
<P>
What happens here?<br>
The server is fetching the current list of earthquakes from
<i>http://neic.usgs.gov/neis/gis/bulletin.asc</i>
and generates a vector map with attributes from that. The result is overlayed to the
Blue Marble Next Generation map from May.


<SMALL><PRE>
</PRE></SMALL>

<br>
<b>Earthquake classification (circles in map are sized by these classes)</b>
<table border="1" cellpadding="2" cellspacing="0">
<tbody><tr>
<td align="center"><b>Magnitude</b></td>
<td align="center"><b>Classification</b></td>
<td align="center"><b>Class for map</b></td>
</tr>
<tr>
<td align="center">0 - 3</td>
<td align="center">Micro</td>
<td align="center">1</td>
</tr>
<tr>
<td align="center">3 - 3.9</td>
<td align="center">Minor</td>
<td align="center">2</td>
</tr>
<tr>
<td align="center">4 - 4.9</td>
<td align="center">Light</td>
<td align="center">3</td>
</tr>
<tr>
<td align="center">5 - 5.9</td>
<td align="center">Moderate</td>
<td align="center">4</td>
</tr>
<tr>
<td align="center">6 - 6.9</td>
<td align="center">Strong</td>
<td align="center">5</td>
</tr>
<tr>
<td align="center">7 - 7.9</td>
<td align="center">Major</td>
<td align="center">6</td>
</tr>
<tr>
<td align="center">8 and higher</td>
<td align="center">Great</td>
<td align="center">7</td>
</tr>
</tbody></table>
<p>
Here a map should appear:<p>

Oldest event from: 
10/11/30 10:45:09
UTC ; Latest event from: 
10/12/07 09:38:31
 UTC <br>
82 earthquakes on this map
<br>
Latest events drawn last.
<p>
<a href="earthquakes.png" border="0"><img src="earthquakes_small.jpg" alt="Auto-generated earthquake map (GRASS GIS/PHP based)"></a><br>
<i>Click for high-res map</i>

<p>
For earthquake details, visit <a href="http://earthquake.usgs.gov/eqcenter/recenteqsww/">Latest Earthquakes in the World - Last 7 days</a> from USGS.
<hr>
2006 Markus Neteler (based on comments from Sharyn Namnath and Glynn Clements)
<br>
<a href="php_grass_earthquakes.txt">Download PHP page source code</a> <br>
<a href="grass_earthquakes.sh">Download the script implemented as SHELL script code</a>
</body>
</html>
